name: Node Typescript QA
on: 
  workflow_call:
    secrets:
      SONARQUBE_KEY:
        required: true
        description: Sonarcloud key
jobs:
  build-and-test:
    name: Build And Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x,16.x,18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint --if-present
      - run: npm test
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.node-version == '16.x' }}
        with:
          name: coverage
          path: |
            coverage
  sonar:
    name: Sonar Scan
    runs-on: ubuntu-latest
    needs:
    - build-and-test
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v3
      with:
        name: coverage
        path: coverage
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONARQUBE_KEY }}