
name: Publish Docs To Github
on: 
  workflow_call:
    inputs:
      publish_docs:
        default: true
        type: boolean
        required: false
      doc_build_task:
        default: build:docs
        type: string
        required: false
      documentation_path:
        default: documentation
        type: string
        required: false
      node_version:
        default: 18.x
        type: string
        required: false
jobs:
  publish-docs: 
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Build Docs
        run: npm run ${{ inputs.doc_build_task }}
      - name: Setup Pages
        if: ${{ inputs.publish_docs == 'true' }}
        uses: actions/configure-pages@v3
      - name: Upload artifact
        if: ${{ inputs.publish_docs == 'true' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: '${{ inputs.documentation_path }}'
      - name: Deploy to GitHub Pages
        if: ${{ inputs.publish_docs == 'true' }}
        id: deployment
        uses: actions/deploy-pages@v2