name: Validate Services
on:
  workflow_call:
    secrets:
      clone_token:
        required: false
        description: A PAT that will be used when cloning
jobs:
  validate-services:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install K3D
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Checkout repository
        if: env.GH_TOKEN
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.clone_token }}
        env:
          GH_TOKEN: ${{ secrets.clone_token }}
      - name: Checkout repository
        if: ${{ !env.GH_TOKEN }}
        uses: actions/checkout@v3
        with:
          submodules: recursive
        env:
          GH_TOKEN: ${{ secrets.clone_token }}
      - name: Start K3D
        run: k3d cluster create test-cluster
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Log into registry
        timeout-minutes: 5
        uses: docker/login-action@40891eba8c2bcd1309b07ba8b11232f313e86779
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Secret in K3D
        run: kubectl create secret docker-registry regcred --docker-username=bryopsida --docker-password=$GITHUB_TOKEN --docker-server=ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Skaffold Build
        run: skaffold build --quiet=true > build.artifacts
      - name: Skaffold Deploy
        run: skaffold deploy -a build.artifacts
      - name: Skaffold Verify
        run: skaffold verify -a build.artifacts
