name: Validate Services
on:
  workflow_call:
    secrets:
      clone_token:
        required: false
        description: A PAT that will be used when cloning
jobs:
  validate-services:
    runs-on: ubuntu-latest
    steps:
      - name: Install K3D
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Checkout repository
        if: env.GH_TOKEN
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.clone_token }}
        env:
          GH_TOKEN: ${{ secrets.clone_token }}
      - name: Checkout repository
        if: ${{ !env.GH_TOKEN }}
        uses: actions/checkout@v3
        with:
          submodules: recursive
        env:
          GH_TOKEN: ${{ secrets.clone_token }}
      - name: Start K3D
        run: k3d cluster create test-cluster
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Skaffold Run
        run: skaffold run
      - name: Create build.artifacts
        run: skaffold build -q > build.artifacts
      - name: Skaffold Verify
        run: skaffold verify -a build.artifacts
