name: Validate Services
on:
  workflow_call:
    secrets:
      clone_pat:
        required: false
        description: A PAT that will be used when cloning
jobs:
  validate-services:
    runs-on: ubuntu-latest
    steps:
      - name: Install K3D
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.clone_pat }}
      - name: Start K3D
        run: k3d cluster create test-cluster
      